export {
  authModeSchema,
  authSchema,
  DEPRECATED_CONFIG_PROPS,
  eventConfigSchema,
  googleAuthSchema,
  insiderEntrySchema,
  isScopeName,
  jeevesConfigSchema,
  keyEntrySchema,
  oauthProviderSchema,
  oauthSchema,
  scopesObjectSchema,
  scopesSchema,
  type AuthMode,
  type JeevesConfig,
} from '@karmaniverous/jeeves-server-core';
